###################################################################

# Created by write_sdc on Sat May  7 12:46:52 2022

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -power mW -voltage V       \
-current mA
set_operating_conditions tt_1p0v_25c -library scadv12_cmos10sf_rvt_tt_1p0v_25c
set_wire_load_mode segmented
set_wire_load_model -name cmos10sf_wl5 -library                                \
scadv12_cmos10sf_rvt_tt_1p0v_25c
set_max_fanout 64 [current_design]
set_load -pin_load 0.009269 [get_ports {read_data[31]}]
set_load -pin_load 0.009269 [get_ports {read_data[30]}]
set_load -pin_load 0.009269 [get_ports {read_data[29]}]
set_load -pin_load 0.009269 [get_ports {read_data[28]}]
set_load -pin_load 0.009269 [get_ports {read_data[27]}]
set_load -pin_load 0.009269 [get_ports {read_data[26]}]
set_load -pin_load 0.009269 [get_ports {read_data[25]}]
set_load -pin_load 0.009269 [get_ports {read_data[24]}]
set_load -pin_load 0.009269 [get_ports {read_data[23]}]
set_load -pin_load 0.009269 [get_ports {read_data[22]}]
set_load -pin_load 0.009269 [get_ports {read_data[21]}]
set_load -pin_load 0.009269 [get_ports {read_data[20]}]
set_load -pin_load 0.009269 [get_ports {read_data[19]}]
set_load -pin_load 0.009269 [get_ports {read_data[18]}]
set_load -pin_load 0.009269 [get_ports {read_data[17]}]
set_load -pin_load 0.009269 [get_ports {read_data[16]}]
set_load -pin_load 0.009269 [get_ports {read_data[15]}]
set_load -pin_load 0.009269 [get_ports {read_data[14]}]
set_load -pin_load 0.009269 [get_ports {read_data[13]}]
set_load -pin_load 0.009269 [get_ports {read_data[12]}]
set_load -pin_load 0.009269 [get_ports {read_data[11]}]
set_load -pin_load 0.009269 [get_ports {read_data[10]}]
set_load -pin_load 0.009269 [get_ports {read_data[9]}]
set_load -pin_load 0.009269 [get_ports {read_data[8]}]
set_load -pin_load 0.009269 [get_ports {read_data[7]}]
set_load -pin_load 0.009269 [get_ports {read_data[6]}]
set_load -pin_load 0.009269 [get_ports {read_data[5]}]
set_load -pin_load 0.009269 [get_ports {read_data[4]}]
set_load -pin_load 0.009269 [get_ports {read_data[3]}]
set_load -pin_load 0.009269 [get_ports {read_data[2]}]
set_load -pin_load 0.009269 [get_ports {read_data[1]}]
set_load -pin_load 0.009269 [get_ports {read_data[0]}]
create_clock [get_ports clk]  -name clock  -period 2  -waveform {0 1}
set_clock_uncertainty 0.1  [get_clocks clock]
set_input_delay -clock clock  -max 0.1  [get_ports reset_n]
set_input_delay -clock clock  -max 0.1  [get_ports cs]
set_input_delay -clock clock  -max 0.1  [get_ports we]
set_input_delay -clock clock  -max 0.1  [get_ports {address[7]}]
set_input_delay -clock clock  -max 0.1  [get_ports {address[6]}]
set_input_delay -clock clock  -max 0.1  [get_ports {address[5]}]
set_input_delay -clock clock  -max 0.1  [get_ports {address[4]}]
set_input_delay -clock clock  -max 0.1  [get_ports {address[3]}]
set_input_delay -clock clock  -max 0.1  [get_ports {address[2]}]
set_input_delay -clock clock  -max 0.1  [get_ports {address[1]}]
set_input_delay -clock clock  -max 0.1  [get_ports {address[0]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[31]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[30]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[29]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[28]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[27]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[26]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[25]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[24]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[23]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[22]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[21]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[20]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[19]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[18]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[17]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[16]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[15]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[14]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[13]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[12]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[11]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[10]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[9]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[8]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[7]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[6]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[5]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[4]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[3]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[2]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[1]}]
set_input_delay -clock clock  -max 0.1  [get_ports {write_data[0]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[31]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[30]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[29]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[28]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[27]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[26]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[25]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[24]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[23]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[22]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[21]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[20]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[19]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[18]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[17]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[16]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[15]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[14]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[13]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[12]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[11]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[10]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[9]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[8]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[7]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[6]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[5]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[4]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[3]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[2]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[1]}]
set_output_delay -clock clock  -max 0.05  [get_ports {read_data[0]}]
